name: Build & Deploy Portfolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch GitHub repo data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p data
          # List of repos
          repos=(
            "abbasmoosajee07/challenge_utils"
            "abbasmoosajee07/AlgoVault"
            "abbasmoosajee07/PlasmaGasifierDP"
            "abbasmoosajee07/TuringMachineSim"
            "abbasmoosajee07/EverybodyCodes"
          )
          
          for repo in "${repos[@]}"; do
            owner=$(echo $repo | cut -d/ -f1)
            name=$(echo $repo | cut -d/ -f2)
            filename="data/${owner}_${name}.json"
            echo "Fetching $repo -> $filename"
            if [ -n "$GH_TOKEN" ]; then
              curl -H "Authorization: token $GH_TOKEN" \
                   https://api.github.com/repos/$repo \
                   > $filename
            else
              curl https://api.github.com/repos/$repo \
                   > $filename
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
